# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaFeeder', '0006_phototag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='coords',
            field=models.CharField(max_length=40),
        ),
    ]
